<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: Workflow Pages: 1 -->
<svg width="1071pt" height="649pt"
 viewBox="0.00 0.00 1071.00 649.40" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 645.4)">
<title>Workflow</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-645.4 1067,-645.4 1067,4 -4,4"/>
<text text-anchor="middle" x="531.5" y="-621.2" font-family="Helvetica,sans-Serif" font-size="18.00">Set_up_coastal_buffer_rasters</text>
<g id="clust1" class="cluster"><title>cluster_workflow_box_outer</title>
<polygon fill="none" stroke="black" stroke-width="2" points="22,-34 22,-577.8 1041,-577.8 1041,-34 22,-34"/>
</g>
<g id="clust2" class="cluster"><title>cluster_workflow_box_inner</title>
<polygon fill="none" stroke="black" stroke-width="0" points="30,-42 30,-569.8 1033,-569.8 1033,-42 30,-42"/>
</g>
<!-- set_up_configuration_and_start_provenance_tracking -->
<g id="node1" class="node"><title>set_up_configuration_and_start_provenance_tracking</title>
<polygon fill="#ccffcc" stroke="black" points="653.784,-489.8 304.216,-489.8 304.216,-453.8 653.784,-453.8 653.784,-489.8"/>
<text text-anchor="middle" x="479" y="-467.6" font-family="Helvetica,sans-Serif" font-size="14.00">set_up_configuration_and_start_provenance_tracking</text>
</g>
<!-- dir_goal -->
<g id="node12" class="node"><title>dir_goal</title>
<path fill="#fcfcfc" stroke="black" d="M556.787,-410.5C556.787,-410.5 515.213,-410.5 515.213,-410.5 509.213,-410.5 503.213,-404.5 503.213,-398.5 503.213,-398.5 503.213,-386.5 503.213,-386.5 503.213,-380.5 509.213,-374.5 515.213,-374.5 515.213,-374.5 556.787,-374.5 556.787,-374.5 562.787,-374.5 568.787,-380.5 568.787,-386.5 568.787,-386.5 568.787,-398.5 568.787,-398.5 568.787,-404.5 562.787,-410.5 556.787,-410.5"/>
<text text-anchor="middle" x="536" y="-388.3" font-family="Helvetica,sans-Serif" font-size="14.00">dir_goal</text>
</g>
<!-- set_up_configuration_and_start_provenance_tracking&#45;&gt;dir_goal -->
<g id="edge2" class="edge"><title>set_up_configuration_and_start_provenance_tracking&#45;&gt;dir_goal</title>
<path fill="none" stroke="black" d="M491.65,-453.645C499.177,-443.437 508.867,-430.296 517.269,-418.902"/>
<polygon fill="black" stroke="black" points="520.267,-420.733 523.385,-410.607 514.633,-416.579 520.267,-420.733"/>
</g>
<!-- dir_spatial -->
<g id="node13" class="node"><title>dir_spatial</title>
<path fill="#fcfcfc" stroke="black" d="M419.784,-331.2C419.784,-331.2 364.216,-331.2 364.216,-331.2 358.216,-331.2 352.216,-325.2 352.216,-319.2 352.216,-319.2 352.216,-307.2 352.216,-307.2 352.216,-301.2 358.216,-295.2 364.216,-295.2 364.216,-295.2 419.784,-295.2 419.784,-295.2 425.784,-295.2 431.784,-301.2 431.784,-307.2 431.784,-307.2 431.784,-319.2 431.784,-319.2 431.784,-325.2 425.784,-331.2 419.784,-331.2"/>
<text text-anchor="middle" x="392" y="-309" font-family="Helvetica,sans-Serif" font-size="14.00">dir_spatial</text>
</g>
<!-- set_up_configuration_and_start_provenance_tracking&#45;&gt;dir_spatial -->
<g id="edge1" class="edge"><title>set_up_configuration_and_start_provenance_tracking&#45;&gt;dir_spatial</title>
<path fill="none" stroke="black" d="M469.524,-453.743C454.292,-426.326 424.264,-372.275 406.38,-340.083"/>
<polygon fill="black" stroke="black" points="409.38,-338.278 401.464,-331.236 403.261,-341.677 409.38,-338.278"/>
</g>
<!-- create_presence_of_buffer_rasters -->
<g id="node2" class="node"><title>create_presence_of_buffer_rasters</title>
<polygon fill="#ccffcc" stroke="black" points="726.843,-331.2 493.157,-331.2 493.157,-295.2 726.843,-295.2 726.843,-331.2"/>
<text text-anchor="middle" x="610" y="-309" font-family="Helvetica,sans-Serif" font-size="14.00">create_presence_of_buffer_rasters</text>
</g>
<!-- rast_3nm_file_handle -->
<g id="node10" class="node"><title>rast_3nm_file_handle</title>
<path fill="#ffffcc" stroke="black" d="M694.814,-251.9C694.814,-251.9 569.186,-251.9 569.186,-251.9 563.186,-251.9 557.186,-245.9 557.186,-239.9 557.186,-239.9 557.186,-227.9 557.186,-227.9 557.186,-221.9 563.186,-215.9 569.186,-215.9 569.186,-215.9 694.814,-215.9 694.814,-215.9 700.814,-215.9 706.814,-221.9 706.814,-227.9 706.814,-227.9 706.814,-239.9 706.814,-239.9 706.814,-245.9 700.814,-251.9 694.814,-251.9"/>
<text text-anchor="middle" x="632" y="-229.7" font-family="Helvetica,sans-Serif" font-size="14.00">rast_3nm_file_handle</text>
</g>
<!-- create_presence_of_buffer_rasters&#45;&gt;rast_3nm_file_handle -->
<g id="edge4" class="edge"><title>create_presence_of_buffer_rasters&#45;&gt;rast_3nm_file_handle</title>
<path fill="none" stroke="black" d="M614.883,-295.045C617.674,-285.237 621.236,-272.722 624.387,-261.65"/>
<polygon fill="black" stroke="black" points="627.76,-262.584 627.131,-252.007 621.027,-260.667 627.76,-262.584"/>
</g>
<!-- rast_1km_file_handle -->
<g id="node11" class="node"><title>rast_1km_file_handle</title>
<path fill="#ffffcc" stroke="black" d="M527.531,-251.9C527.531,-251.9 402.469,-251.9 402.469,-251.9 396.469,-251.9 390.469,-245.9 390.469,-239.9 390.469,-239.9 390.469,-227.9 390.469,-227.9 390.469,-221.9 396.469,-215.9 402.469,-215.9 402.469,-215.9 527.531,-215.9 527.531,-215.9 533.531,-215.9 539.531,-221.9 539.531,-227.9 539.531,-227.9 539.531,-239.9 539.531,-239.9 539.531,-245.9 533.531,-251.9 527.531,-251.9"/>
<text text-anchor="middle" x="465" y="-229.7" font-family="Helvetica,sans-Serif" font-size="14.00">rast_1km_file_handle</text>
</g>
<!-- create_presence_of_buffer_rasters&#45;&gt;rast_1km_file_handle -->
<g id="edge5" class="edge"><title>create_presence_of_buffer_rasters&#45;&gt;rast_1km_file_handle</title>
<path fill="none" stroke="black" d="M577.82,-295.045C556.701,-283.786 528.888,-268.959 506.163,-256.844"/>
<polygon fill="black" stroke="black" points="507.561,-253.623 497.09,-252.007 504.268,-259.8 507.561,-253.623"/>
</g>
<!-- read_in_buffer_shapfiles_if_rasters_not -->
<g id="node3" class="node"><title>read_in_buffer_shapfiles_if_rasters_not</title>
<polygon fill="#ccffcc" stroke="black" points="595.847,-172.6 334.153,-172.6 334.153,-136.6 595.847,-136.6 595.847,-172.6"/>
<text text-anchor="middle" x="465" y="-150.4" font-family="Helvetica,sans-Serif" font-size="14.00">read_in_buffer_shapfiles_if_rasters_not</text>
</g>
<!-- rast_3nm_file -->
<g id="node4" class="node"><title>rast_3nm_file</title>
<path fill="#ffffcc" stroke="black" d="M174.79,-50.5C174.79,-50.5 505.21,-50.5 505.21,-50.5 511.21,-50.5 517.21,-56.5 517.21,-62.5 517.21,-62.5 517.21,-88.1 517.21,-88.1 517.21,-94.1 511.21,-100.1 505.21,-100.1 505.21,-100.1 174.79,-100.1 174.79,-100.1 168.79,-100.1 162.79,-94.1 162.79,-88.1 162.79,-88.1 162.79,-62.5 162.79,-62.5 162.79,-56.5 168.79,-50.5 174.79,-50.5"/>
<text text-anchor="middle" x="340" y="-83.5" font-family="Helvetica,sans-Serif" font-size="14.00">rast_3nm_file</text>
<polyline fill="none" stroke="black" points="162.79,-75.3 517.21,-75.3 "/>
<text text-anchor="middle" x="340" y="-58.7" font-family="Helvetica,sans-Serif" font-size="14.00">file:{dir_goal}/spatial/hs_offshore_3nm_raster_500m.tif</text>
</g>
<!-- read_in_buffer_shapfiles_if_rasters_not&#45;&gt;rast_3nm_file -->
<g id="edge8" class="edge"><title>read_in_buffer_shapfiles_if_rasters_not&#45;&gt;rast_3nm_file</title>
<path fill="none" stroke="black" d="M437.258,-136.445C422.559,-127.354 404.097,-115.938 387.22,-105.501"/>
<polygon fill="black" stroke="black" points="388.913,-102.432 378.567,-100.15 385.231,-108.386 388.913,-102.432"/>
</g>
<!-- rast_1km_file -->
<g id="node5" class="node"><title>rast_1km_file</title>
<path fill="#ffffcc" stroke="black" d="M546.795,-50.5C546.795,-50.5 863.205,-50.5 863.205,-50.5 869.205,-50.5 875.205,-56.5 875.205,-62.5 875.205,-62.5 875.205,-88.1 875.205,-88.1 875.205,-94.1 869.205,-100.1 863.205,-100.1 863.205,-100.1 546.795,-100.1 546.795,-100.1 540.795,-100.1 534.795,-94.1 534.795,-88.1 534.795,-88.1 534.795,-62.5 534.795,-62.5 534.795,-56.5 540.795,-50.5 546.795,-50.5"/>
<text text-anchor="middle" x="705" y="-83.5" font-family="Helvetica,sans-Serif" font-size="14.00">rast_1km_file</text>
<polyline fill="none" stroke="black" points="534.795,-75.3 875.205,-75.3 "/>
<text text-anchor="middle" x="705" y="-58.7" font-family="Helvetica,sans-Serif" font-size="14.00">file:{dir_goal}/spatial/hs_inland_1km_raster_500m.tif</text>
</g>
<!-- read_in_buffer_shapfiles_if_rasters_not&#45;&gt;rast_1km_file -->
<g id="edge9" class="edge"><title>read_in_buffer_shapfiles_if_rasters_not&#45;&gt;rast_1km_file</title>
<path fill="none" stroke="black" d="M517.966,-136.54C548.249,-126.787 586.918,-114.332 621.227,-103.282"/>
<polygon fill="black" stroke="black" points="622.332,-106.603 630.778,-100.206 620.186,-99.9401 622.332,-106.603"/>
</g>
<!-- rast_3nm_file_output_port -->
<g id="node18" class="node"><title>rast_3nm_file_output_port</title>
<ellipse fill="#ffffff" stroke="black" cx="340" cy="-7" rx="7" ry="7"/>
</g>
<!-- rast_3nm_file&#45;&gt;rast_3nm_file_output_port -->
<g id="edge19" class="edge"><title>rast_3nm_file&#45;&gt;rast_3nm_file_output_port</title>
<path fill="none" stroke="black" d="M340,-50.3642C340,-41.694 340,-32.1105 340,-24.2546"/>
<polygon fill="black" stroke="black" points="343.5,-24.0006 340,-14.0006 336.5,-24.0007 343.5,-24.0006"/>
</g>
<!-- rast_1km_file_output_port -->
<g id="node19" class="node"><title>rast_1km_file_output_port</title>
<ellipse fill="#ffffff" stroke="black" cx="705" cy="-7" rx="7" ry="7"/>
</g>
<!-- rast_1km_file&#45;&gt;rast_1km_file_output_port -->
<g id="edge20" class="edge"><title>rast_1km_file&#45;&gt;rast_1km_file_output_port</title>
<path fill="none" stroke="black" d="M705,-50.3642C705,-41.694 705,-32.1105 705,-24.2546"/>
<polygon fill="black" stroke="black" points="708.5,-24.0006 705,-14.0006 701.5,-24.0007 708.5,-24.0006"/>
</g>
<!-- setup.R -->
<g id="node6" class="node"><title>setup.R</title>
<path fill="#ffffcc" stroke="black" d="M499.236,-561.8C499.236,-561.8 458.764,-561.8 458.764,-561.8 452.764,-561.8 446.764,-555.8 446.764,-549.8 446.764,-549.8 446.764,-537.8 446.764,-537.8 446.764,-531.8 452.764,-525.8 458.764,-525.8 458.764,-525.8 499.236,-525.8 499.236,-525.8 505.236,-525.8 511.236,-531.8 511.236,-537.8 511.236,-537.8 511.236,-549.8 511.236,-549.8 511.236,-555.8 505.236,-561.8 499.236,-561.8"/>
<text text-anchor="middle" x="479" y="-539.6" font-family="Helvetica,sans-Serif" font-size="14.00">setup.R</text>
</g>
<!-- setup.R&#45;&gt;set_up_configuration_and_start_provenance_tracking -->
<g id="edge3" class="edge"><title>setup.R&#45;&gt;set_up_configuration_and_start_provenance_tracking</title>
<path fill="none" stroke="black" d="M479,-525.497C479,-517.783 479,-508.512 479,-499.912"/>
<polygon fill="black" stroke="black" points="482.5,-499.904 479,-489.904 475.5,-499.904 482.5,-499.904"/>
</g>
<!-- rast_base -->
<g id="node7" class="node"><title>rast_base</title>
<path fill="#ffffcc" stroke="black" d="M684.47,-367.7C684.47,-367.7 977.53,-367.7 977.53,-367.7 983.53,-367.7 989.53,-373.7 989.53,-379.7 989.53,-379.7 989.53,-405.3 989.53,-405.3 989.53,-411.3 983.53,-417.3 977.53,-417.3 977.53,-417.3 684.47,-417.3 684.47,-417.3 678.47,-417.3 672.47,-411.3 672.47,-405.3 672.47,-405.3 672.47,-379.7 672.47,-379.7 672.47,-373.7 678.47,-367.7 684.47,-367.7"/>
<text text-anchor="middle" x="831" y="-400.7" font-family="Helvetica,sans-Serif" font-size="14.00">rast_base</text>
<polyline fill="none" stroke="black" points="672.47,-392.5 989.53,-392.5 "/>
<text text-anchor="middle" x="831" y="-375.9" font-family="Helvetica,sans-Serif" font-size="14.00">file:{dir_spatial}/raster/ohibc_rgn_raster_500m.tif</text>
</g>
<!-- rast_base&#45;&gt;create_presence_of_buffer_rasters -->
<g id="edge7" class="edge"><title>rast_base&#45;&gt;create_presence_of_buffer_rasters</title>
<path fill="none" stroke="black" d="M762.889,-367.677C732.58,-357.075 697.255,-344.72 668.201,-334.557"/>
<polygon fill="black" stroke="black" points="669.199,-331.198 658.604,-331.2 666.888,-337.806 669.199,-331.198"/>
</g>
<!-- poly_3nm_file -->
<g id="node8" class="node"><title>poly_3nm_file</title>
<path fill="#ffffcc" stroke="black" d="M50.0064,-209.1C50.0064,-209.1 339.994,-209.1 339.994,-209.1 345.994,-209.1 351.994,-215.1 351.994,-221.1 351.994,-221.1 351.994,-246.7 351.994,-246.7 351.994,-252.7 345.994,-258.7 339.994,-258.7 339.994,-258.7 50.0064,-258.7 50.0064,-258.7 44.0064,-258.7 38.0064,-252.7 38.0064,-246.7 38.0064,-246.7 38.0064,-221.1 38.0064,-221.1 38.0064,-215.1 44.0064,-209.1 50.0064,-209.1"/>
<text text-anchor="middle" x="195" y="-242.1" font-family="Helvetica,sans-Serif" font-size="14.00">poly_3nm_file</text>
<polyline fill="none" stroke="black" points="38.0064,-233.9 351.994,-233.9 "/>
<text text-anchor="middle" x="195" y="-217.3" font-family="Helvetica,sans-Serif" font-size="14.00">file:{dir_spatial}/howe_sound_offshore_3nm.shp</text>
</g>
<!-- poly_3nm_file&#45;&gt;read_in_buffer_shapfiles_if_rasters_not -->
<g id="edge11" class="edge"><title>poly_3nm_file&#45;&gt;read_in_buffer_shapfiles_if_rasters_not</title>
<path fill="none" stroke="black" d="M278.212,-209.077C315.886,-198.291 359.902,-185.689 395.74,-175.429"/>
<polygon fill="black" stroke="black" points="396.969,-178.718 405.619,-172.6 395.042,-171.988 396.969,-178.718"/>
</g>
<!-- poly_1km_file -->
<g id="node9" class="node"><title>poly_1km_file</title>
<path fill="#ffffcc" stroke="black" d="M737.012,-209.1C737.012,-209.1 1012.99,-209.1 1012.99,-209.1 1018.99,-209.1 1024.99,-215.1 1024.99,-221.1 1024.99,-221.1 1024.99,-246.7 1024.99,-246.7 1024.99,-252.7 1018.99,-258.7 1012.99,-258.7 1012.99,-258.7 737.012,-258.7 737.012,-258.7 731.012,-258.7 725.012,-252.7 725.012,-246.7 725.012,-246.7 725.012,-221.1 725.012,-221.1 725.012,-215.1 731.012,-209.1 737.012,-209.1"/>
<text text-anchor="middle" x="875" y="-242.1" font-family="Helvetica,sans-Serif" font-size="14.00">poly_1km_file</text>
<polyline fill="none" stroke="black" points="725.012,-233.9 1024.99,-233.9 "/>
<text text-anchor="middle" x="875" y="-217.3" font-family="Helvetica,sans-Serif" font-size="14.00">file:{dir_spatial}/howe_sound_inland_1km.shp</text>
</g>
<!-- poly_1km_file&#45;&gt;read_in_buffer_shapfiles_if_rasters_not -->
<g id="edge12" class="edge"><title>poly_1km_file&#45;&gt;read_in_buffer_shapfiles_if_rasters_not</title>
<path fill="none" stroke="black" d="M748.641,-209.077C689.721,-197.968 620.586,-184.934 565.322,-174.514"/>
<polygon fill="black" stroke="black" points="565.646,-171.014 555.17,-172.6 564.349,-177.893 565.646,-171.014"/>
</g>
<!-- rast_3nm_file_handle&#45;&gt;read_in_buffer_shapfiles_if_rasters_not -->
<g id="edge13" class="edge"><title>rast_3nm_file_handle&#45;&gt;read_in_buffer_shapfiles_if_rasters_not</title>
<path fill="none" stroke="black" d="M594.937,-215.745C570.289,-204.336 537.726,-189.263 511.365,-177.061"/>
<polygon fill="black" stroke="black" points="512.504,-173.732 501.959,-172.707 509.564,-180.084 512.504,-173.732"/>
</g>
<!-- rast_1km_file_handle&#45;&gt;read_in_buffer_shapfiles_if_rasters_not -->
<g id="edge14" class="edge"><title>rast_1km_file_handle&#45;&gt;read_in_buffer_shapfiles_if_rasters_not</title>
<path fill="none" stroke="black" d="M465,-215.745C465,-206.137 465,-193.932 465,-183.03"/>
<polygon fill="black" stroke="black" points="468.5,-182.707 465,-172.707 461.5,-182.707 468.5,-182.707"/>
</g>
<!-- dir_goal&#45;&gt;create_presence_of_buffer_rasters -->
<g id="edge6" class="edge"><title>dir_goal&#45;&gt;create_presence_of_buffer_rasters</title>
<path fill="none" stroke="black" d="M552.423,-374.345C562.483,-363.836 575.518,-350.22 586.64,-338.601"/>
<polygon fill="black" stroke="black" points="589.236,-340.951 593.623,-331.307 584.179,-336.111 589.236,-340.951"/>
</g>
<!-- dir_spatial&#45;&gt;read_in_buffer_shapfiles_if_rasters_not -->
<g id="edge10" class="edge"><title>dir_spatial&#45;&gt;read_in_buffer_shapfiles_if_rasters_not</title>
<path fill="none" stroke="black" d="M384.372,-294.857C376.107,-273.244 365.977,-235.842 381,-208.6 388.104,-195.718 399.802,-185.536 412.243,-177.685"/>
<polygon fill="black" stroke="black" points="414.054,-180.68 420.927,-172.617 410.526,-174.634 414.054,-180.68"/>
</g>
<!-- setup.R_input_port -->
<g id="node14" class="node"><title>setup.R_input_port</title>
<ellipse fill="#ffffff" stroke="black" cx="479" cy="-604.8" rx="7" ry="7"/>
</g>
<!-- setup.R_input_port&#45;&gt;setup.R -->
<g id="edge15" class="edge"><title>setup.R_input_port&#45;&gt;setup.R</title>
<path fill="none" stroke="black" d="M479,-597.486C479,-591.286 479,-581.395 479,-571.848"/>
<polygon fill="black" stroke="black" points="482.5,-571.816 479,-561.816 475.5,-571.816 482.5,-571.816"/>
</g>
<!-- poly_3nm_file_input_port -->
<g id="node15" class="node"><title>poly_3nm_file_input_port</title>
<ellipse fill="#ffffff" stroke="black" cx="7" cy="-313.2" rx="7" ry="7"/>
</g>
<!-- poly_3nm_file_input_port&#45;&gt;poly_3nm_file -->
<g id="edge16" class="edge"><title>poly_3nm_file_input_port&#45;&gt;poly_3nm_file</title>
<path fill="none" stroke="black" d="M11.2849,-307.463C14.8984,-303.706 20.3689,-298.547 26,-295.2 48.2217,-281.991 73.795,-271.009 98.2119,-262.199"/>
<polygon fill="black" stroke="black" points="99.5911,-265.424 107.864,-258.805 97.269,-258.82 99.5911,-265.424"/>
</g>
<!-- poly_1km_file_input_port -->
<g id="node16" class="node"><title>poly_1km_file_input_port</title>
<ellipse fill="#ffffff" stroke="black" cx="1056" cy="-313.2" rx="7" ry="7"/>
</g>
<!-- poly_1km_file_input_port&#45;&gt;poly_1km_file -->
<g id="edge17" class="edge"><title>poly_1km_file_input_port&#45;&gt;poly_1km_file</title>
<path fill="none" stroke="black" d="M1051.7,-307.484C1048.08,-303.738 1042.61,-298.586 1037,-295.2 1015.44,-282.182 990.597,-271.218 966.949,-262.361"/>
<polygon fill="black" stroke="black" points="967.848,-258.963 957.254,-258.82 965.446,-265.539 967.848,-258.963"/>
</g>
<!-- rast_base_input_port -->
<g id="node17" class="node"><title>rast_base_input_port</title>
<ellipse fill="#ffffff" stroke="black" cx="1056" cy="-471.8" rx="7" ry="7"/>
</g>
<!-- rast_base_input_port&#45;&gt;rast_base -->
<g id="edge18" class="edge"><title>rast_base_input_port&#45;&gt;rast_base</title>
<path fill="none" stroke="black" d="M1051.77,-465.975C1048.18,-462.167 1042.73,-456.983 1037,-453.8 1011.94,-439.872 983.343,-428.87 955.592,-420.292"/>
<polygon fill="black" stroke="black" points="956.403,-416.881 945.819,-417.358 954.391,-423.586 956.403,-416.881"/>
</g>
</g>
</svg>
